### ISSUE TITLE
Overlay breaks because "cannot find module './sge.png'

### ISSUE THREAD

**Issue by Crazyjim27** [bsides/horizoverlay#144]
Overlay will not display information when a sage is in the party and will just turn off. I noticed the ACT was giving the reason I put in the title

I am also using what I believe to be the most up to date URL: https://bsides.github.io/horizoverlay

**Comment by ekumlin** [comment]
This is fixed by #143 but needs an approval from a contributor like @bsides.

**Comment by bsides** [comment]
> Overlay will not display information when a sage is in the party and will just turn off. I noticed the ACT was giving the reason I put in the title
> 
> I am also using what I believe to be the most up to date URL: https://bsides.github.io/horizoverlay

Thanks for contributing!

> This is fixed by #143 but needs an approval from a contributor like @bsides.

It's approved and merged.

I'll close this for now, but please reopen the issue in case it doesn't work.

**Comment by Tene21** [comment]
I'm still getting this issue. Made sure I'm using the up-to-date URL, hit "reload overlay" who knows how many times, overlay still just blinks out of existence as soon as I cast Dosis.

**Comment by ngld** [comment]
The code is updated and fixed but the `gh-pages` branch isn't which means that the github.io URL still contains the outdated (broken) version.
@bsides will have to update that branch as well before the overlay works again.

**Comment by bsides** [comment]
I will look into into today in a couple of hours. Thanks @ngld

**Comment by Tene21** [comment]
Any ETA on when this will be fixed?

**Comment by bsides** [comment]
Yes @Tene21 I posted above just that. Should be fixed now.

Thank you all for your hard work.
